server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
spring:
  application:
    name: catalog-service
  config:
#    add optional if you want to run the application without the config server: optional:configserver:.
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8888
