server:
  port: ${PORT:9001}
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
spring:
  application:
    name: catalog-service
#  sql:
#    init:
#      mode: always
  datasource:
    username: ${DATASOURCE_USERNAME:user}
    password: ${DATASOURCE_PASSWORD:password}
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5435/cns_db}
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  config:
#    add optional if you want to run the application without the config server: optional:configserver:.
#    import: "configserver:"
    import: "optional:configserver:"
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false # In production, set to true
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1
management:
  endpoints:
    web:
      exposure:
        include: refresh

my:
  greeting: Welcome to the local book catalog!