server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
spring:
  application:
    name: catalog-service
  sql:
    init:
      mode: always
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5435/cns_db
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  config:
#    add optional if you want to run the application without the config server: optional:configserver:.
    import: "configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1

management:
  endpoints:
    web:
      exposure:
        include: refresh
